---
- name: Install Nginx/Apache
  hosts: all
  become: yes
  tasks:
       -name: Install Nginx
        apt:
           name: nginx
           state: latest
       -name: index.html
        action: copy=index.html dest=/var/www/html/
